name: style-check

concurrency:
  group: style-check-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branch:
      - main
  pull_request:
    branch:
      - main
  schedule:
    - cron: "0 0 * * 1/2" # Every other day 12AM UTC

env:
  LINES: 200
  COLUMNS: 200

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!github.event.repository.fork" # Don't run on fork repository
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup CI
        uses: ./.github/actions/setup-repo
      - name: Install development dependencies and bindings
        run: |
          bazel run //requirements:pypi.update
          python -m pip install -r requirements/pypi.txt
      - name: Format check
        run: |
          black --check src
          isort --check .
      - name: Lint check
        run: ruff check src
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "17"
      - name: Install pyright
        shell: bash
        run: npm install -g npm@^7 pyright
      - name: Type check
        if: ${{ github.event_name == 'pull_request' }}
        run: git diff --name-only --diff-filter=AM "origin/$GITHUB_BASE_REF" -z -- '*.py{,i}' | xargs -0 --no-run-if-empty pyright
